amqp:
  host: ${AMQP_RABBIT_HOST}
  port: ${AMQP_RABBIT_PORT}
  username: ${AMQP_RABBIT_USERNAME}
  password: ${AMQP_RABBIT_PASSWORD}

keycloak:
  host: ${KEYCLOAK_HOST:http://localhost:8443}
  realm: ${KEYCLOAK_REALM:fc3-codeflix}

mysql:
  username: ${DATABASE_MYSQL_USERNAME:root}
  password: ${DATABASE_MYSQL_PASSWORD:root}
  schema: admin_video
  url: ${DATABASE_MYSQL_URL:localhost:3306}


spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

