amqp:
  host: localhost
  port: 5672
  username: adm_videos
  password: 123456

keycloak:
  host: http://test:8443
  realm: test

logging:
  level:
    ROOT: info

mysql:
  username: root
  password: root
  schema: admin_video
  url: localhost:${mysql.port}


spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
