amqp:
  admin:
    auto-create: true
  host: localhost
  port: 5672
  username: adm_videos
  password: 123456

keycloak:
    host: http://localhost:8443
    realm: fc3-codeflix

mysql:
  username: root
  password: root
  schema: admin_video
  url: localhost:3306


server:
  port: 8080
  undertow:
    threads:
      worker: 10
      io: 2
