version: '3.7'

services:
  mysql:
    container_name: admin_video_mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: admin_video
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      - admin_video_network

networks:
  admin_video_network:
