version: '3.7'

services:
  mysql:
    container_name: admin_video_mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: admin_video
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      - admin_video_network

  rabbitmq:
    container_name: adm_videos_rabbitmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=adm_videos
      - RABBITMQ_DEFAULT_PASS=123456
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - admin_video_network

networks:
  admin_video_network:
