version: '3.7'

services:
  app:
    container_name: admin_video_app
    build:
      context: ../../
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - "8080:8080"
    networks:
      - admin_video_network
      - admin_video_services
    depends_on:
      - filebeat
    labels:
      filebeat_collector: true

  filebeat:
    container_name: adm_videos_filebeat
    image: docker.elastic.co/beats/filebeat:7.17.9
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
      - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro # Configuration file
      - ../.docker/filebeat:/usr/share/filebeat/data:rw                    # Persistence data
    user: root                                                             # Allow access to log files and docker.sock
    restart: on-failure
    networks:
      - admin_video_network
      - elastic

networks:
  admin_video_network:
  admin_video_services:
    external: true
  elastic:
    external: true
